custom_data:
    probe_fasta_link:
        section_name: '🧬'
        file_format: 'html'
        plot_type: 'html'
        target: 'probe_download.md'

    probe_summary:
        file_format: 'csv'
        section_name: 'Probe Design Summary'
        plot_type: 'table'
        pconfig:
            id: 'probe_summary'
            title: 'Custom Probes Used for rRNA Depletion'
        
    test_probes_rrna_reduction:
        plot_type: 'bargraph'
        file_format: 'csv'
        section_name: 'Probes test in-silico: rRNA reduction by extra probes'
        categories:
            rRNA Depletion Percent:
                name: "rRNA Depletion Percent"
                color: "#274472"
        pconfig:
            id: 'rRNA_reduction_extra_probes'
            title: 'rRNA Reduction by Extra Probes'
            ylab: 'Estimated rRNA Reduction (%)'
            ymin: 0
            ymax: 100
    
    test_probes_composition:
        plot_type: 'bargraph'
        file_format: 'csv'
        section_name: 'Probes test in-silico: Read composition'
        categories:
            Remaining rRNA:
                name: "Remaining rRNA"
                color: "#dd8452"
            Depleted:
                name: "Depleted"
                color: "#4c72b0"
            Unmapped:
                name: "Unmapped"
                color: "#999999"
        pconfig:
            id: 'read_composition_by_sample'
            title: 'Read Composition by Sample'
            ylab: 'Read Count'
            stacking: 'normal'

sp:
    probe_fasta_link:
        fn: 'probe_download.md'
    probe_summary:
        fn: 'probes_summary.csv'
    test_probes_rrna_reduction:
        fn: 'test_probes_rrna_reduction.csv'
    test_probes_composition:
        fn: 'test_probes_composition.csv'
